name: psma
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=1.2.6
  - matplotlib=3.1.3
  - notebook=6.0.3
  - numpy=1.18.1
  - pandas=1.0.1
  - pip=20.0.2
  - python=3.7.3
  - scipy=1.4.1
  - seaborn=0.10.0
  - statsmodels=0.11.1
  - pip:
    - pmdarima==1.5.3
    - scikit-learn==0.22.1
    - sklearn==0.0
